#!/bin/sh
#shellcheck disable=SC2034
#
# Tool to install and/or patch Yume 2kki
#

print_debug_vars(){
	printf '
	this script does not cleanup on INT SIGTERM or die()
	here are what paths are set to should you want to check/delete them
		working directory:  %s
		output directory:   %s
		game path:          %s
		patch file:         %s
		actual game folder: %s
	\n' "$work_dir" "$out_dir" "$game_path" "$patch_file" "$real_game_dir" >&2
}

write_debug(){
	printf '%s: %s\n' "${0##*/}" "$1"
}

die(){
	write_debug "$1" >&2
	print_debug_vars
	exit 1
}

usage(){
	printf '
	%s [-d] [-7 PATCH|GAME|BOTH] -g ARCHIVE|DIRECTORY [-p ARCHIVE] [-o DIRECTORY] [-w DIRECTORY]

		-g     select game directory/archive
		-p     select patch archive
		-o     set custom output directory
		-w     set custom working directory

		-d     remove working directory after installation
		-7     use 7z extractor for PATCH, GAME or BOTH

	-o will default to the game path if the game is a directory and -o is unset
	if using -p you must provide an archive
	if using -g without -p the game must be an archive
	-o cannot be the same as -w or -g

	N.B: 7zip is unlikely to create a useable installation of Yume 2kki if
	the archive is not a .7z
	\n' "${0##*/}" >&2
	exit 1
}

#shellcheck disable=SC2038
cicp(){
	_src="$1"
	_dest="$2"

	find "$_src" -mindepth 1 -maxdepth 1 -type d | while read -r src_dir ; do
		src_base="$(basename "$src_dir")"
		if [ -d "$_dest/$src_base" ]; then
			cp -R "$src_dir" "$_dest"
		else
			ci_match="$(find "$_dest" -mindepth 1 -maxdepth 1 -type d -iname "$src_base")"
			if [ "$(printf '%s\n' "$ci_match" | wc -l | tr -d '[:space:]')" -gt 1 ]; then
				write_debug "WARNING: more than one match found for case insensitive move: $src_dir" >&2
				printf '%s\n' "$ci_match" | while read -r conflict; do
					write_debug "conflict: $conflict" >&2
				done
				continue
			fi
			if [ -n "$ci_match" ]; then
				cp -R "$src_dir"/* "$ci_match"
			else
				cp -R "$src_dir" "$_dest"
			fi
		fi
	done

	find "$_src" -mindepth 1 -maxdepth 1 -type f | xargs -I _ cp _ "$_dest"
}

determine_real_game_dir(){
	_ldb_path="$(find "$1" -type f -name 'RPG_RT.ldb')"
	_actual_game_path="$(realpath -q "${_ldb_path%/*}" 2>/dev/null)"

	[ -z "$_actual_game_path" ] || [ ! -f "$_actual_game_path/RPG_RT.ini" ] ||
		[ "$(printf  '%s\n' "$_ldb_path" | wc -l)" -gt 1 ] &&
			die "unable to determine real 2kki directory: $1"

	printf '%s' "$_actual_game_path"
}

convert_to_opus(){
	_no_conv=0
	_target_dir="$1"
	_bitrate="$2"

	[ ! -d "$_target_dir" ] && return 1

	_no_files="$(find "$_target_dir" -type f -iname '*.wav' | wc -l | \
		tr -d '[:space:]')"

	write_debug 'converting WAVs'

	# convert normal wavs
	find "$_target_dir" -type f -iname '*.wav' | while read -r file; do
		printf '\r\t%03d%% complete' "$((100 * _no_conv / _no_files))"

		opusenc --vbr --bitrate "$_bitrate" "$file" "${file%.*}.opus" >/dev/null 2>&1 ||
			# convert abpcm
			ffmpeg -nostdin -i "$file" -acodec pcm_s16le -f wav - 2>/dev/null | \
			opusenc --vbr --bitrate "$_bitrate" - "${file%.*}.opus" >/dev/null 2>&1 &&
			rm "$file"

		_no_conv="$((_no_conv + 1))"
	done ; printf '\033[K\r'

	_no_files="$(find "$_target_dir" -type f -iname '*.mp3' | wc -l | \
		tr -d '[:space:]')"

	write_debug 'converting MP3s'

	# convert mp3s
	find "$_target_dir" -type f -iname '*.mp3' | while read -r file; do
		printf '\r\t%03d%% complete' "$((100 * _no_conv / _no_files))"

		lame --decode "$file" - 2>/dev/null | \
			opusenc --vbr --bitrate "$_bitrate" - "${file%.*}.opus" >/dev/null 2>&1 &&
			rm "$file"

		_no_conv="$((_no_conv + 1))"
	done ; printf '\033[K\r'
}

install_rtp(){
	_rtp_dir="$1"

	mkdir -p "$_rtp_dir/raw"
	[ ! -d "$_rtp_dir/raw" ] && die "unable to create subdirectory: $_rtp_dir/raw"

	write_debug 'downloading RTP archives'

	curl -sSfLO --output-dir "$_rtp_dir" "https://tkool.jp/products/rtp/2000rtp.zip" >/dev/null
	curl -sSfLO --output-dir "$_rtp_dir" "https://tkool.jp/products/rtp/RTP_patchk_190612.zip" >/dev/null

	[ ! -f "$_rtp_dir/2000rtp.zip" ] || [ ! -f "$_rtp_dir/RTP_patchk_190612.zip" ] &&
		die 'RTP could not be downloaded'

	write_debug 'unpacking RTP'

	# this was mainly adapted from the pkgbuild for rpg2000-rtp
	# written by carstene1ns from easyrpg <arch carsten-teibes de>
	# http://git.io/ctPKG

	# unpack
	unar -e ms932 "$_rtp_dir/2000rtp.zip" -o "$_rtp_dir/raw" -q >/dev/null 2>&1
	unar "$_rtp_dir/raw/RTPｾｯﾄｱｯﾌﾟ/RPG2000RTP.exe" -o "$_rtp_dir/raw" -q >/dev/null 2>&1
	unshield -e ms932 -d "$_rtp_dir/raw/rtp" x "$_rtp_dir/raw/RPG2000RTP/data1.cab" >/dev/null 2>&1
	unar -e ms932 "$_rtp_dir/RTP_patchk_190612.zip" -o "$_rtp_dir/raw" -q >/dev/null 2>&1
	mv "$_rtp_dir/raw/rtp/RPGﾂｸｰﾙ2000_ﾗﾝﾀｲﾑﾊﾟｯｹｰｼﾞ" "$_rtp_dir/raw/2000"

	write_debug 'patching RTP'

	# convert text
	iconv -f ms932 -t UTF-8 "$_rtp_dir/raw/RTPｾｯﾄｱｯﾌﾟ/使用規約.txt" > "$_rtp_dir/raw/使用規約.txt"
	iconv -f ms932 -t UTF-8 "$_rtp_dir/raw/RTP_patchk_190612/RTPの修正ファイルについて.txt" > "$_rtp_dir/raw/RTPの修正ファイルについて.txt"
	# apply patch
	mv "$_rtp_dir/raw/RTP_patchk_190612/モンスター.png" "$_rtp_dir/raw/2000/RTP/FaceSet"
	mv "$_rtp_dir/raw/RTP_patchk_190612/主人公3.png" "$_rtp_dir/raw/2000/RTP/CharSet"
	for img_name in '基本' 'ダンジョン' '船' '内装' '外観'; do
		mv "$_rtp_dir/raw/RTP_patchk_190612/$img_name.png" "$_rtp_dir/raw/2000/RTP/ChipSet"
	done

	rm "$_rtp_dir/RTP_patchk_190612.zip" "$_rtp_dir/2000rtp.zip"
	mv "$_rtp_dir/raw/2000/RTP"/* "$_rtp_dir"
	rm -Rf "$_rtp_dir/raw"
}

install_language(){
	_yno_translations_url='https://github.com/ynoproject/ynotranslations/archive/refs/heads/master.zip'
	_trans_dir="$1"

	mkdir -p "$_trans_dir/raw"
	[ ! -d "$_trans_dir/raw" ] && die "unable to create subdirectory: $_trans_dir/raw"

	write_debug 'downloading YNO translations'

	curl -sSfLo "$_trans_dir/out.zip" "$_yno_translations_url"
	unar -e ms932 "$_trans_dir/out.zip" -o "$_trans_dir/raw" -q >/dev/null 2>&1
	mv "$_trans_dir/raw/ynotranslations-master/2kki"/* "$_trans_dir"
	rm -Rf "$_trans_dir/raw" "$_trans_dir/out.zip"
}

exec_dir="$PWD"
work_dir="$exec_dir/2kki-install-working"
out_dir="$exec_dir/2kki-install-output"

while getopts :dw:o:g:p:7: OPT ; do case "$OPT" in
	o)
	       out_dir="$(realpath -q "$OPTARG" 2>/dev/null)"
	       is_out_dir_changed=1
	       ;;
	w)
	       work_dir="$(realpath -q "$OPTARG" 2>/dev/null)"
	       is_work_dir_changed=1
	       ;;
	g) game_path="$(realpath -q "$OPTARG" 2>/dev/null)" ;;
	p) patch_file="$(realpath -q "$OPTARG" 2>/dev/null)" ;;
	d) delete_work_dir=1 ;;
	7) use_7zip="$OPTARG" ;;
	?) usage ;;
esac done

for dep in 'curl' 'unar' 'unshield' 'opusenc' 'ffmpeg' 'lame'; do
	! command -v $dep >/dev/null 2>&1 && die "missing dependency: $dep"
done

[ -z "$game_path" ] && die 'missing a game path'
[ -z "$patch_file" ] && [ -d "$game_path" ] && die 'solitary game folders currently must be an archive'
[ -d "$patch_file" ] && die 'currently the patch must be an archive'

[ "$work_dir" = "$out_dir" ] &&
	die 'working directory and output directory cannot be the same'
[ "$game_path" = "$out_dir" ] || [ "$game_path" = "$work_dir" ] &&
	die 'game path cannot be the output/working directory'

[ -z "$is_out_dir_changed" ] && [ -d "$out_dir" ] && die 'output directory already exists'
[ -z "$is_out_dir_changed" ] && [ -d "$work_dir" ] && die 'working directory already exists'

[ -n "$use_7zip" ] && case "$use_7zip" in
	BOTH|GAME|PATCH) : ;;
	*) usage ;;
esac

mkdir -p "$work_dir"
mkdir -p "$out_dir"
[ ! -d "$work_dir" ] && die 'failure making working directory'
[ ! -d "$out_dir" ] && die 'failure making output directory'

# trap print_debug_vars INT TERM

for temp_work_dir in 'game' 'rtp' 'lang' 'patch'; do
	mkdir -p "$work_dir/$temp_work_dir"
	[ ! -d "$work_dir/$temp_work_dir" ] &&
		die 'temporary working directories could not be created'
done

if [ -f "$game_path" ]; then
	write_debug 'extracting game archive'
	if [ "$use_7zip" = 'GAME' ] || [ "$use_7zip" = 'BOTH' ]; then
		! 7z -mmt x "$game_path" -o"$work_dir/game" &&
			die 'error extracting game archive'
	else
		! unar -e ms932 "$game_path" -o "$work_dir/game" -D &&
			die 'error extracting game archive'
	fi

	write_debug 'determining real game directory'
	real_game_dir="$(determine_real_game_dir "$work_dir/game")"
elif [ -d "$game_path" ]; then
	write_debug 'determining real game directory'
	real_game_dir="$(determine_real_game_dir "$game_path")"
else
	die 'game path is neither an archive nor a directory'
fi

if [ "$is_out_dir_changed" = '1' ] && [ -d "$game_path" ]; then
	write_debug 'moving real game path to output directory'
	cp -R "$real_game_dir"/* "$out_dir"
	real_game_dir="$out_dir"
fi

install_rtp "$work_dir/rtp"
write_debug 'case-insensitively installing RTP'
cicp "$work_dir/rtp" "$real_game_dir"
rm -Rf "$work_dir/rtp"

if [ ! -e "$real_game_dir/Language" ]; then
	install_language "$work_dir/lang"
	write_debug 'installing languages'
	mv "$work_dir/lang" "$real_game_dir/Language"
	[ ! -d "$real_game_dir/Language" ] &&
		die "unable to create subdirectory: $real_game_dir/Language"
	rm -Rf "$work_dir/lang"
fi

write_debug 'converting music to opus'
convert_to_opus "$real_game_dir/Music" 85
write_debug 'converting sound files to opus'
convert_to_opus "$real_game_dir/Sound" 50

if [ -f "$patch_file" ]; then
	write_debug 'extracting patch'
	if [ "$use_7zip" = 'PATCH' ] || [ "$use_7zip" = 'BOTH' ]; then
		! 7z -mmt x "$patch_file" -o"$work_dir/patch" &&
			die 'error extracting patch archive'
	else
		! unar -e ms932 "$patch_file" -o "$work_dir/patch" -D &&
			die 'error extracting patch archive'
	fi

	write_debug 'determining real patch directory'
	real_patch_dir="$(determine_real_game_dir "$work_dir/patch")"

	write_debug 'converting music to opus'
	convert_to_opus "$real_patch_dir/Music" 85
	write_debug 'converting sound files to opus'
	convert_to_opus "$real_patch_dir/Sound" 50

	write_debug 'case-insensitively applying patch to game files'
	cicp "$real_patch_dir" "$real_game_dir"
	rm -Rf "$work_dir/patch"
fi

write_debug 'patching RPG_RT.ini'
sed -i 's/MapEditZoom=.*/MapEditZoom=0/;/^WinW=/d;/^WinH=/d' "$real_game_dir/RPG_RT.ini"
write_debug 'removing RPG_RT.exe'
rm "$real_game_dir/RPG_RT.exe"

if [ ! "$out_dir" = "$game_path" ]; then
	write_debug 'moving game files to output directory'
	mv "$real_game_dir"/* "$out_dir"
fi

if [ "$delete_work_dir" = '1' ]; then
	write_debug 'removing working directory'
	rm -Rf "$work_dir"
fi

write_debug "successfully installed Yume 2kki to: $out_dir"

exit 0
