#!/bin/sh
#shellcheck disable=SC2086
#shellcheck disable=SC2046
#shellcheck disable=SC2034
#
# Tool to install and/or patch Yume 2kki
#

#shellcheck disable=SC2329
print_debug_vars(){
	printf '
	this script does not cleanup on EXIT INT SIGTERM or die()
	here are what paths are set to should you want to check/delete them
		working directory:  %s
		output directory:   %s
		game path:          %s
		patch file:         %s
		actual game folder: %s
	\n' "$work_dir" "$out_dir" "$game_path" "$patch_file" "$real_game_dir" >&2
}

write_debug(){
	printf '%s: %s\n' "${0##*/}" "$1"
}


die(){
	write_debug "$1" >&2
	exit 1
}

usage(){
	printf '
	%s [-d] -g ARCHIVE|DIRECTORY [-p ARCHIVE] [-o DIRECTORY] [-w DIRECTORY]

		-g     select game directory/archive
		-p     select patch archive
		-o     set custom output directory
		-w     set custom working directory

		-d     remove working directory after installation

	-o will default to the game path if the game is a directory and -o is unset
	if using -p you must provide an archive
	if using -g without -p the game must be an archive
	-o cannot be the same as -w or -g
	\n' "${0##*/}" >&2
	exit 1
}

determine_real_game_dir(){
	_ldb_path="$(find "$1" -type f -name 'RPG_RT.ldb')"
	_actual_game_path="$(realpath -q "${_ldb_path%/*}" 2>/dev/null)"

	[ -z "$_actual_game_path" ] || [ ! -f "$_actual_game_path/RPG_RT.ini" ] ||
		[ "$(printf  '%s\n' "$_ldb_path" | wc -l)" -gt 1 ] && return 1

	printf '%s' "$_actual_game_path"
}

convert_to_opus(){
	_target_dir="$1"
	_bitrate="$2"

	[ ! -d "$_target_dir" ] && return 1

	# convert normal wavs
	find "$_target_dir" -type f -iname '*.wav' | while read -r file; do
		opusenc --vbr --bitrate "$_bitrate" "$file" "${file%.*}.opus" ||
			# convert abpcm
			ffmpeg -nostdin -i "$file" -acodec pcm_s16le -f wav - | \
			opusenc --vbr --bitrate "$_bitrate" - "${file%.*}.opus" &&
			rm "$file"
	done

	# convert mp3s
	find "$_target_dir" -type f -iname '*.mp3' | while read -r file; do
		lame --decode "$file" - | \
			opusenc --vbr --bitrate "$_bitrate" - "${file%.*}.opus" &&
			rm "$file"
	done
}

install_rtp(){
	_rtp_dir="$1"

	write_debug 'downloading RTP archives'

	curl -sSfLO --output-dir "$_rtp_dir" "https://tkool.jp/products/rtp/2000rtp.zip" >/dev/null
	curl -sSfLO --output-dir "$_rtp_dir" "https://tkool.jp/products/rtp/RTP_patchk_190612.zip" >/dev/null

	[ ! -f "$_rtp_dir/2000rtp.zip" ] || [ ! -f "$_rtp_dir/RTP_patchk_190612.zip" ] && die 'RTP could not be downloaded'

	write_debug 'patching RTP'

	# this was mainly adapted from the pkgbuild for rpg2000-rtp
	# written by carstene1ns from easyrpg <arch carsten-teibes de>
	# http://git.io/ctPKG

	# unpack
	unar -e ms932 "$_rtp_dir/2000rtp.zip" -o "$_rtp_dir" -q >/dev/null 2>&1
	unar "$_rtp_dir/RTPｾｯﾄｱｯﾌﾟ/RPG2000RTP.exe" -o "$_rtp_dir" -q >/dev/null 2>&1
	unshield -e ms932 -d "$_rtp_dir/rtp" x "$_rtp_dir/RPG2000RTP/data1.cab" >/dev/null 2>&1
	unar -e ms932 "$_rtp_dir/RTP_patchk_190612.zip" -o "$_rtp_dir" -q >/dev/null 2>&1
	mv "$_rtp_dir/rtp/RPGﾂｸｰﾙ2000_ﾗﾝﾀｲﾑﾊﾟｯｹｰｼﾞ" "$_rtp_dir/2000"
	# convert text
	iconv -f ms932 -t UTF-8 "$_rtp_dir/RTPｾｯﾄｱｯﾌﾟ/使用規約.txt" > "$_rtp_dir/使用規約.txt"
	iconv -f ms932 -t UTF-8 "$_rtp_dir/RTP_patchk_190612/RTPの修正ファイルについて.txt" > "$_rtp_dir/RTPの修正ファイルについて.txt"
	# apply patch
	mv "$_rtp_dir/RTP_patchk_190612/モンスター.png" "$_rtp_dir/2000/RTP/FaceSet"
	mv "$_rtp_dir/RTP_patchk_190612/主人公3.png" "$_rtp_dir/2000/RTP/CharSet"
	for img_name in '基本' 'ダンジョン' '船' '内装' '外観'; do
		mv "$_rtp_dir/RTP_patchk_190612/$img_name.png" "$_rtp_dir/2000/RTP/ChipSet"
	done
}

install_language(){
	_yno_translations_url='https://github.com/ynoproject/ynotranslations/archive/refs/heads/master.zip'
	_trans_dir="$1"

	write_debug 'downloading YNO translations'

	curl -sSfLo "$_trans_dir/out.zip" "$_yno_translations_url"
	unar -e ms932 "$_trans_dir/out.zip" -o "$_trans_dir/raw" -q >/dev/null 2>&1
	rm "$_trans_dir/out.zip"
	cp -R "$_trans_dir/raw/ynotranslations-master/2kki" "$_trans_dir"
	rm -Rf "$_trans_dir/raw"
}

exec_dir="$PWD"
work_dir="$exec_dir/2kki-install-working"
out_dir="$exec_dir/2kki-install-output"

while getopts dw:o:g:p: opt ; do case "$opt" in
	g)
	       game_path="$(realpath -q "$OPTARG" 2>/dev/null)"
	       ;;
	p)
	       patch_file="$(realpath -q "$OPTARG" 2>/dev/null)"
	       ;;
	o)
	       out_dir="$(realpath -q "$OPTARG" 2>/dev/null)"
	       is_out_dir_changed=1
	       ;;
	w)
	       work_dir="$(realpath -q "$OPTARG" 2>/dev/null)"
	       is_work_dir_changed=1
	       ;;
	d)
		delete_work_dir=1
		;;
	?) usage ;;
esac done

for dep in 'unar' 'unshield' 'opusenc' 'ffmpeg' 'lame'; do
	! command -v $dep >/dev/null 2>&1 && die "missing dependency: $dep"
done

[ -z "$game_path" ] && die 'missing a game path'
[ -z "$patch_file" ] && [ -d "$game_path" ] && die 'solitary game folders currently must be an archive'
[ -d "$patch_file" ] && die 'currently the patch must be an archive'

[ -z "$is_out_dir_changed" ] && [ -d "$out_dir" ] && die 'output directory already exists'
[ -z "$is_out_dir_changed" ] && [ -d "$work_dir" ] && die 'working directory already exists'
mkdir -p "$work_dir"
mkdir -p "$out_dir"
[ ! -d "$work_dir" ] && die 'failure making working directory'
[ ! -d "$out_dir" ] && die 'failure making output directory'

[ "$work_dir" = "$out_dir" ] &&
	die 'working directory and output directory cannot be the same'
[ "$game_path" = "$out_dir" ] || [ "$game_path" = "$work_dir" ] &&
	die 'game path cannot be the output/working directory'

trap print_debug_vars EXIT INT TERM

for temp_work_dir in 'game' 'rtp' 'lang' 'patch'; do
	mkdir -p "$work_dir/$temp_work_dir"
	[ ! -d "$work_dir/$temp_work_dir" ] &&
		die 'temporary working directories could not be created'
done

if [ -f "$game_path" ]; then
	write_debug 'extracting game archive'
	! unar -e ms932 "$game_path" -o "$work_dir/game" -D -q >/dev/null 2>&1 &&
		die 'error extracting game archive'

	write_debug 'determining real game directory'
	real_game_dir="$(! determine_real_game_dir "$work_dir/game" &&
		die 'unable to determine real game directory')"
elif [ -d "$game_path" ]; then
	write_debug 'determining real game directory'
	real_game_dir="$(! determine_real_game_dir "$game_path" &&
		die 'unable to determine real game directory')"
else
	die 'game path is not an archive or a directory'
fi

if [ "$is_out_dir_changed" = '1' ] && [ -d "$game_path" ]; then
	write_debug 'moving real game path to output directory'
	cp -R "$real_game_dir"/* "$out_dir"
	real_game_dir="$out_dir"
fi

install_rtp "$work_dir/rtp"
write_debug 'installing RTP'
cp -R "$work_dir/rtp" "$real_game_dir"
rm -Rf "$work_dir/rtp"

install_language "$work_dir/lang"
write_debug 'installing languages'
mv "$work_dir/lang/2kki" "$real_game_dir/Language"
rm -Rf "$work_dir/lang"

write_debug 'converting music to opus'
! convert_to_opus "$real_game_dir/Music" 85 >/dev/null 2>&1 &&
	write_debug "skipping converting $real_game_dir/Music"
write_debug 'converting sound files to opus'
! convert_to_opus "$real_game_dir/Sound" 50 >/dev/null 2>&1 &&
	write_debug "skipping converting $real_game_dir/Sound"

if [ -f "$patch_file" ]; then
	write_debug 'extracting patch'
	! unar -e ms932 "$patch_file" -o "$work_dir/patch" -D -q >/dev/null 2>&1 &&
		die 'error extracting patch archive'

	write_debug 'determining real patch directory'
	real_patch_dir="$(! determine_real_game_dir "$work_dir/patch" &&
		die 'unable to determine real patch directory')"

	write_debug 'converting music to opus'
	! convert_to_opus "$real_patch_dir/Music" 85 >/dev/null 2>&1 &&
		write_debug "skipping converting $real_patch_dir/Music"
	write_debug 'converting sound files to opus'
	! convert_to_opus "$real_patch_dir/Sound" 50 >/dev/null 2>&1 &&
		write_debug "skipping converting $real_patch_dir/Sound"

	write_debug 'applying patch to game files'
	cp -R "$real_patch_dir"/* "$real_game_dir"
	rm -Rf "$work_dir/patch"
fi

write_debug 'patching RPG_RT.ini'
sed -i 's/MapEditZoom=.*/MapEditZoom=0/;/^WinW=/d;/^WinH=/d' "$real_game_dir/RPG_RT.ini"
rm "$real_game_dir/RPG_RT.exe"

if [ ! "$out_dir" = "$game_path" ]; then
	write_debug 'moving game files to output directory'
	mv "$real_game_dir"/* "$out_dir"
fi

if [ "$delete_work_dir" = '1' ]; then
	write_debug 'removing working directory'
	rm -Rf "$work_dir"
fi

trap - EXIT

write_debug "successfully installed Yume 2kki to: $out_dir"

exit 0
